### PR TITLE
pass along throwIfMockNotDefined

### PR DESCRIPTION
**Pull request by abloom**
cc @mcculloughsean

### CODE REVIEW

**Comment by mcculloughsean** [comment]
:+1: 
Looks like the style settings are new.

**Comment by relekang** [comment]
Thanks :)

**Comment by relekang** [comment]
@mcculloughsean Yeah, I fixed the warnings in master.

Also, uploaded a new release on npm :tada:

**Comment by mcculloughsean** [comment]
Thanks @relekang!

**Comment by abloom** [comment]
thanks @relekang

**Pull request merged**
